version: '3'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    platform: linux/arm64
    ports:
      - "4444:4444"
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-limit", "5", "-timeout", "5m", "-service-startup-timeout", "5m"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    platform: linux/amd64
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  ggr:
    image: aerokube/ggr:latest
    network_mode: bridge
    platform: linux/amd64
    ports:
      - "4445:4444"
    volumes:
      - ~/selenoid/users:/etc/grid-router/users
      - ~/selenoid/users/users.htpasswd:/etc/grid-router/users.htpasswd
      - ~/selenoid/quota:/etc/grid-router/quota
      - "./users:/etc/grid-router/users"
      - "./quota.xml:/etc/grid-router/quota/quota.xml"